# Generated by Django 3.2.20 on 2025-03-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_payment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrpayment',
            name='qr_code_url',
        ),
        migrations.AddField(
            model_name='qrpayment',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AddField(
            model_name='qrpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
    ]
