# Generated by Django 3.2.20 on 2025-03-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qr_payment', '0002_auto_20250303_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpayment',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
