# Generated by Django 3.2.20 on 2025-03-20 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_payment', '0003_qrpayment_qr_code_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrpayment',
            name='qr_code_url',
        ),
        migrations.RemoveField(
            model_name='qrpayment',
            name='reference',
        ),
        migrations.RemoveField(
            model_name='qrpayment',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='qrpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='qrpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qr_payments', to=settings.AUTH_USER_MODEL),
        ),
    ]
