# Generated by Django 3.2.20 on 2025-03-20 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qr_payment', '0004_auto_20250320_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrpayment',
            name='qr_code_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrpayment',
            name='reference',
            field=models.CharField(default='DEFAULT_VALUE', max_length=255),
        ),
        migrations.AddField(
            model_name='qrpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='qrpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('failed', 'Fallido')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='qrpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
