# Generated by Django 3.2.20 on 2025-03-19 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_register', '0002_user_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_register',
            name='user',
        ),
    ]
