# Generated by Django 3.2.20 on 2025-02-19 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country_region',
        ),
    ]
