# Generated by Django 4.2.20 on 2025-04-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='postal_zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='age',
            field=models.CharField(default='18', max_length=10),
        ),
    ]
