# Generated by Django 4.2.20 on 2025-03-22 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0019_auto_20250313_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
            },
        ),
        migrations.CreateModel(
            name='StockPorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_sucursal', to='product.product')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_por_producto', to='branches.sucursal')),
            ],
            options={
                'verbose_name': 'Stock por sucursal',
                'verbose_name_plural': 'Stock por sucursal',
                'db_table': 'stock_por_sucursal',
                'unique_together': {('producto', 'sucursal')},
            },
        ),
    ]
