# Generated by Django 3.2.20 on 2025-03-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20250228_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(null=True),
        ),
    ]
