# Generated by Django 3.2.20 on 2025-03-07 15:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_productimage_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mayorista_tipo', models.IntegerField(choices=[(0, 'Cliente Normal'), (1, 'Mayorista 1'), (2, 'Mayorista 2'), (3, 'Mayorista 3')], default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='product.product')),
            ],
            options={
                'unique_together': {('product', 'mayorista_tipo')},
            },
        ),
    ]
