# Generated by Django 3.2.20 on 2025-03-09 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20250307_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_mayorista_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='price_mayorista_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AddField(
            model_name='product',
            name='price_mayorista_3',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
