# Generated by Django 3.2.20 on 2025-03-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20250308_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price_mayorista_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_mayorista_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_mayorista_3',
        ),
        migrations.AlterField(
            model_name='product',
            name='compare_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
