# Generated by Django 3.2.20 on 2025-02-23 15:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=20, unique=True)),
                ('foto_anverso_ci', models.ImageField(upload_to='preregistro/ci_anverso/')),
                ('foto_reverso_ci', models.ImageField(upload_to='preregistro/ci_reverso/')),
                ('numero_celular', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('actividad_economica', models.TextField()),
                ('fecha_registro', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
            ],
        ),
    ]
