# Generated by Django 4.2.20 on 2025-04-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioAnalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('sentimiento', models.CharField(max_length=50)),
                ('fecha_analisis', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
