# Generated by Django 4.2.20 on 2025-05-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0003_sentimentanalysis_delete_comentarioanalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentimentanalysis',
            name='categoria',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='cleaned_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='flag_agresivo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='precio_producto',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='probability_agresivo',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='sucursal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='tipo_mayorista',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='sentiment',
            field=models.CharField(max_length=20),
        ),
    ]
